### ISSUE TITLE
Question about IMU data

### ISSUE THREAD

**Issue by xiaobrnbrn** [Abekabe/IMU-Dead-Reckoning#1]
Hello,
I have tested my own data with the package, but the accumulated error of the localization results have increased quickly. In my test, the input was IMU raw data, is that reasonable? Looking for your reply.

**Comment by Abekabe** [comment]
Sorry for the late reply.
Since we integrate the linear acceleration and angular velocities to position, the error would accumulate and propagate. We usually use IMU dead reckoning in local (like in one second) or between two precise local update (GPS, LiDAR localization).

You can refer to [LOAM](https://www.ri.cmu.edu/pub_files/2014/7/Ji_LidarMapping_RSS2014_v8.pdf) and [VIO](https://www.research-collection.ethz.ch/bitstream/handle/20.500.11850/236658/1/RSS2013paper.pdf) to know how the IMU dead reckoning is used in robotics.
